force-app/main/default/objects/MySetting__c/MySetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MySetting</label>
</CustomObject>

force-app/main/default/objects/MySetting__c/fields/On__c.field-meta.xml
<CustomField>
    <fullName>On__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FlowAction.cls
public with sharing class FlowAction {
  @InvocableMethod(label='Get Account Names' description='Returns the list of account names corresponding to the specified account IDs.')
  public static List<String> getAccountNames(List<ID> ids) {
    List<String> accountNames = new List<String>();
    List<Account> accounts = [SELECT Name FROM Account WHERE Id in :ids];
    for (Account account : accounts) {
      accountNames.add(account.Name);
    }
    MySetting__c s = [select On__c from MySetting__c];
    return accountNames;
  }
}